/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TopoGraph copy.vue')['default']
    DropGraph: typeof import('./src/components/DropGraph.vue')['default']
    EatGraph: typeof import('./src/components/EatGraph.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FlowGraph: typeof import('./src/components/FlowGraph.vue')['default']
    HistoryGraph: typeof import('./src/components/HistoryGraph.vue')['default']
    NewTopoGraph: typeof import('./src/components/NewTopoGraph.vue')['default']
    QueueGraph: typeof import('./src/components/QueueGraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SwitchCard: typeof import('./src/components/SwitchCard.vue')['default']
    SwitchList: typeof import('./src/components/SwitchList.vue')['default']
    Topo: typeof import('./src/components/topo.vue')['default']
    TopoDemo: typeof import('./src/components/TopoDemo.vue')['default']
    TopoGraph: typeof import('./src/components/TopoGraph.vue')['default']
  }
}
